# Generated by Django 5.2.3 on 2025-12-20 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0041_exercise_draft_notes_exercise_is_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_instructions', models.TextField(blank=True, help_text="Teacher's guidance about what to extract (e.g., 'Only exercises 7-12')")),
                ('status', models.CharField(choices=[('analyzing', 'Analyzing'), ('active', 'Active'), ('completed', 'Completed')], default='analyzing', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authoring_sessions', to='exercises.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authoring_sessions', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, help_text='Created during chat after teacher confirms module name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authoring_sessions', to='exercises.module')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(help_text='MIME type: application/pdf, text/plain, etc.', max_length=100)),
                ('file_data', models.BinaryField(help_text='Binary file content')),
                ('size_bytes', models.IntegerField()),
                ('page_count', models.IntegerField(blank=True, help_text='Number of pages (for PDFs only)', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='authoring_tools.authoringsession')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='authoringsession',
            index=models.Index(fields=['course', 'created_by', 'status'], name='authsess_crs_usr_stat_idx'),
        ),
        migrations.AddConstraint(
            model_name='authoringsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['analyzing', 'active'])), fields=('course', 'created_by'), name='one_active_session_per_teacher_per_course'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['session', 'uploaded_at'], name='upfile_session_time_idx'),
        ),
    ]
