# Generated by Django 5.2.3 on 2025-12-20 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_tools', '0001_initial'),
        ('exercises', '0041_exercise_draft_notes_exercise_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoringsession',
            name='segmentation_data',
            field=models.JSONField(blank=True, help_text='Latest segmentation JSON from Phase 1 (module name, exercises list)', null=True),
        ),
        migrations.AlterField(
            model_name='authoringsession',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Created during Phase 2 after teacher confirms', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authoring_sessions', to='exercises.module'),
        ),
        migrations.AlterField(
            model_name='authoringsession',
            name='status',
            field=models.CharField(choices=[('analyzing', 'Analyzing'), ('active', 'Active'), ('building', 'Building'), ('completed', 'Completed')], default='analyzing', max_length=20),
        ),
    ]
