# Generated by Django 5.2.9 on 2025-12-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_tools', '0002_authoringsession_segmentation_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoringsession',
            name='error_message',
            field=models.TextField(blank=True, help_text="Error message if status is 'timeout' or 'error'"),
        ),
        migrations.AlterField(
            model_name='authoringsession',
            name='status',
            field=models.CharField(choices=[('analyzing', 'Analyzing'), ('active', 'Active'), ('building', 'Building'), ('completed', 'Completed'), ('timeout', 'Timeout'), ('error', 'Error')], default='analyzing', max_length=20),
        ),
    ]
