# Generated by Django 5.2.9 on 2025-12-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_tools', '0003_authoringsession_error_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoringsession',
            name='teacher_instructions',
        ),
        migrations.AddField(
            model_name='authoringsession',
            name='cache_name',
            field=models.CharField(blank=True, help_text='Gemini cache name for context caching (question generator)', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='gemini_file_uri',
            field=models.CharField(blank=True, help_text="Gemini File API URI for this file (e.g., 'files/abc123')", max_length=500),
        ),
    ]
