# Generated by Django 5.2.9 on 2025-12-22 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring_tools', '0004_remove_authoringsession_teacher_instructions_and_more'),
        ('exercises', '0044_remove_course_chat_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authoringsession',
            name='one_active_session_per_teacher_per_course',
        ),
        migrations.AlterField(
            model_name='authoringsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('building', 'Building'), ('completed', 'Completed'), ('error', 'Error')], default='active', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='authoringsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'building'])), fields=('course', 'created_by'), name='one_active_session_per_teacher_per_course'),
        ),
    ]
