# Generated by Django 5.2.3 on 2025-08-31 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name/title of the course that will be displayed to the user.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='A short description of the course that will be displayed to the user.')),
                ('llm_prompts', models.JSONField(blank=True, default=dict, help_text="LLM prompts per exercise type, e.g. {'turtle': 'Your prompt for turtle exercises...'}")),
                ('visible', models.BooleanField(default=True, help_text='Whether the course is visible to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name/title of the module that will be displayed to the user.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='A short description of the module that will be displayed to the user.')),
                ('order', models.PositiveIntegerField(default=0, help_text='The order of the module within the course.')),
                ('visible', models.BooleanField(default=True, help_text='Whether the module is visible to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='exercises.course')),
            ],
            options={
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the exercice; not displayed to the user.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the exercice; not displayed to the user.')),
                ('exercise_type', models.CharField(choices=[('python', 'Python'), ('multiple_choice', 'Multiple Choice'), ('sql', 'SQL'), ('turtle', 'Turtle'), ('open_question', 'Open Question')], default='python', help_text="Type of the exercice, e.g. 'multiple_choice', 'text', 'turtle', etc.", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='The order of the exercice within the course.')),
                ('exercise_data', models.JSONField(help_text='Contains fields like question, data-source, etc.')),
                ('answer_data', models.JSONField(default=dict, help_text='Contains fields like expected_result, hints, etc.')),
                ('visible', models.BooleanField(default=True, help_text='Whether the exercise is visible to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.module')),
            ],
            options={
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'order')},
            },
        ),
        migrations.CreateModel(
            name='StudentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Lowercased', max_length=254, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_invite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False, help_text='True if the user has completed the exercise.')),
                ('version', models.IntegerField(default=1, help_text='Version of the trace, can be used to track changes in the trace logic or prompt or eval version.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_prompt', models.TextField(blank=True, help_text='The system prompt sent to the LLM for this trace, if debugging is enabled.', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exercise', 'version')},
            },
        ),
        migrations.CreateModel(
            name='GuidanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.JSONField(help_text="Stores the user's submission and the LLM's response for a single turn.")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_logs', to='exercises.trace')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceEval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ok', models.BooleanField(help_text='Whether the trace is considered correct or not. Null means not evaluated.', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback provided for this evaluation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_evals', to='exercises.trace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Filename like 'shop.sql', 'presentation.pptx'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description.', null=True)),
                ('content', models.BinaryField(help_text='Store any file type as binary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='exercises.course')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'course'), name='unique_name_per_course')],
            },
        ),
    ]
