# Generated by Django 5.2.3 on 2025-09-02 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name/title of the course that will be displayed to the user.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='A short description of the course that will be displayed to the user.')),
                ('chat_prompt', models.TextField(blank=True, help_text='Chatbot-specific instructions for this course, when the user starts a chat thread.')),
                ('llm_prompts', models.JSONField(blank=True, default=dict, help_text="LLM prompts per exercise type, e.g. {'turtle': 'Your prompt for turtle exercises...'}")),
                ('visible', models.BooleanField(default=True, help_text='Whether the course is visible to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the exercice; not displayed to the user.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the exercice; not displayed to the user.')),
                ('exercise_type', models.CharField(choices=[('python', 'Python'), ('multiple_choice', 'Multiple Choice'), ('sql', 'SQL'), ('turtle', 'Turtle'), ('open_question', 'Open Question')], default='python', help_text="Type of the exercice, e.g. 'multiple_choice', 'text', 'turtle', etc.", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='The order of the exercice within the course.')),
                ('exercise_data', models.JSONField(help_text='Contains fields like question, data-source, etc.')),
                ('answer_data', models.JSONField(default=dict, help_text='Contains fields like expected_result, hints, etc.')),
                ('visible', models.BooleanField(default=True, help_text='Whether the exercise is visible to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False, help_text='True if the user has completed the exercise.')),
                ('version', models.IntegerField(default=1, help_text='Version of the attempt, can be used to track changes in the attempt logic or prompt or eval version.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_prompt', models.TextField(blank=True, help_text='The system prompt sent to the LLM for this attempt, if debugging is enabled.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttemptEval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ok', models.BooleanField(help_text='Whether the attempt is considered correct or not. Null means not evaluated.', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback provided for this evaluation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='exercises.attempt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.JSONField(help_text="Stores the user's submission and the LLM's response for a single turn.")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='exercises.attempt')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-friendly cohort name.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, help_text='Optional short code for joining this cohort.', max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cohorts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='exercises.cohort'),
        ),
        migrations.CreateModel(
            name='CohortMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=20)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_members_added', to=settings.AUTH_USER_MODEL)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='exercises.cohort')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('cohort', 'student')},
            },
        ),
        migrations.AddField(
            model_name='cohort',
            name='students',
            field=models.ManyToManyField(related_name='cohorts', through='exercises.CohortMembership', through_fields=('cohort', 'student'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cohort',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='exercises.course'),
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title shown in the thread list.', max_length=255)),
                ('messages', models.JSONField(blank=True, default=list, help_text="Ordered array of chat messages, just like in OpenAI's API.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(help_text='Each chat thread is associated with a course.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='exercises.course')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Filename like 'shop.sql', 'presentation.pptx'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description.', null=True)),
                ('content', models.BinaryField(help_text='Store any file type as binary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='exercises.course')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exercises.exercise'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name/title of the module that will be displayed to the user.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='A short description of the module that will be displayed to the user.')),
                ('order', models.PositiveIntegerField(default=0, help_text='The order of the module within the course.')),
                ('visible', models.BooleanField(default=True, help_text='Whether the module is visible to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='exercises.course')),
            ],
            options={
                'ordering': ['course', 'order'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.module'),
        ),
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Lowercased', max_length=254, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_invite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='unique_cohort_name_per_course'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('course', 'code'), name='unique_cohort_code_per_course'),
        ),
        migrations.AddConstraint(
            model_name='exerciceasset',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='unique_name_per_course'),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('user', 'exercise', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('module', 'order')},
        ),
    ]
