# Generated by Django 5.2.3 on 2025-09-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_move_question_to_top_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='completion_feedback',
            field=models.JSONField(blank=True, help_text='The structured feedback and next exercise recommendations from the LLM upon completing an exercise.', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_data',
            field=models.JSONField(help_text='Contains fields like data-source, etc.'),
        ),
    ]
