# Generated by Django 5.2.3 on 2025-09-07 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exercises', '0004_attempt_completion_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='system_prompt',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('python', 'Python'), ('open_question', 'Open Question'), ('sql', 'SQL'), ('turtle', 'Turtle'), ('scala', 'Scala')], default='python', help_text="Type of the exercice, e.g. 'open_question', 'python', 'scala', 'sql', 'turtle', etc.", max_length=50),
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('system_prompt', models.TextField(blank=True, help_text='The system prompt sent to the LLM for this trace. Only set on the first trace.', null=True)),
                ('assistant_content', models.TextField(blank=True, help_text="The assistant's response to the user's message.")),
                ('assistant_metadata', models.JSONField(blank=True, default=dict, help_text="Metadata about the assistant's response, like the LLM response time, model, etc.")),
                ('user_content', models.TextField(blank=True, help_text="The user's message to the assistant.")),
                ('user_metadata', models.JSONField(blank=True, default=dict, help_text="Metadata about the user's message, like the action, the question, the answer, the code, the output, the error message, etc.")),
                ('rank_order', models.SmallIntegerField(default=0, help_text="The order of the trace within the owning entity's conversation.")),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='AttemptInteraction',
        ),
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=['content_type', 'object_id'], name='exercises_t_content_74a1ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='trace',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'rank_order'), name='unique_trace_rank_per_owner'),
        ),
    ]
