# Generated by Django 5.2.3 on 2025-09-07 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_attempt_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
