# Generated by Django 5.2.3 on 2025-09-08 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_traceeval_delete_attempteval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohortmembership',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='cohortmembership',
            unique_together={('cohort', 'user')},
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='students',
        ),
        migrations.AddField(
            model_name='cohortmembership',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('assistant', 'Assistant'), ('owner', 'Owner')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='If set, the user will be added to this cohort upon registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_invites', to='exercises.cohort'),
        ),
        migrations.AlterField(
            model_name='cohortmembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='traceeval',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback provided for this evaluation.', null=True),
        ),
        migrations.AddConstraint(
            model_name='cohortmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('cohort',), name='unique_cohort_owner'),
        ),
    ]
