# Generated by Django 5.2.3 on 2025-09-08 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_cohort_membership_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='members',
            field=models.ManyToManyField(related_name='cohorts', through='exercises.CohortMembership', through_fields=('cohort', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
