# Generated by Django 5.2.3 on 2025-09-09 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_cohort_members_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciceAsset',
            new_name='ExerciseAsset',
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cohortmembership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chatthread',
            name='messages',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('python', 'Python'), ('open_question', 'Open Question'), ('sql', 'SQL'), ('turtle', 'Turtle'), ('scala', 'Scala')], default='python', help_text="Type of the exercise, e.g. 'open_question', 'python', 'scala', 'sql', 'turtle', etc.", max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The order of the exercise within the course.'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'updated_at'], name='attempt_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'complete', 'updated_at'], name='attempt_user_coplt_pdtd_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['cohort', 'user'], name='attempt_cohort_user_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['owner', 'updated_at'], name='chathread_owner_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['owner', 'course', 'updated_at'], name='chat_owner_course_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='cohortmembership',
            index=models.Index(fields=['cohort', 'role'], name='cohort_role_idx'),
        ),
        migrations.AddIndex(
            model_name='cohortmembership',
            index=models.Index(fields=['user', 'role'], name='cm_user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='cohortmembership',
            index=models.Index(fields=['user', 'status', 'joined_at'], name='cm_user_status_joined_idx'),
        ),
        migrations.AddIndex(
            model_name='cohortmembership',
            index=models.Index(fields=['cohort', 'status'], name='cm_cohort_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['module', 'visible'], name='exercise_module_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseasset',
            index=models.Index(fields=['course', 'name'], name='asset_course_name_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'visible'], name='module_course_visible_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('user', 'exercise', 'version'), name='unique_attempt_per_user_exercise_version'),
        ),
        migrations.AddConstraint(
            model_name='cohortmembership',
            constraint=models.UniqueConstraint(fields=('cohort', 'user'), name='unique_membership_per_cohort_user'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_exercise_order_per_module'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_module_order_per_course'),
        ),
    ]
