# Generated by Django 5.2.3 on 2025-09-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_coursemembership_course_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvite',
            name='note',
        ),
    ]
