# Generated by Django 5.2.3 on 2025-09-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_remove_userinvite_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='completion_feedback',
        ),
    ]
