# Generated by Django 5.2.3 on 2025-09-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_remove_attempt_completion_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('python', 'Python'), ('open_question', 'Open Question'), ('sql', 'SQL'), ('turtle', 'Turtle'), ('scala', 'Scala')], default='python', help_text="Type of the exercise, e.g. 'open_question', 'python', 'scala', 'sql', 'turtle', etc.", max_length=50),
        ),
    ]
