# Generated by Django 5.2.3 on 2025-09-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_alter_exercise_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='asked_for_solution',
            field=models.BooleanField(default=False, help_text='True if the user has asked for the solution.'),
        ),
    ]
