# Generated by Django 5.2.3 on 2025-09-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_remove_multiple_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The order of the exercise within its module.'),
        ),
    ]
