# Generated by Django 5.2.3 on 2025-09-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0018_course_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_quiz',
            field=models.BooleanField(default=False, help_text='Whether this module is a quiz module.'),
        ),
    ]
