# Generated by Django 5.2.3 on 2025-09-28 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_module_is_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student_count', models.IntegerField(help_text='Number of students who participated')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_logs', to='exercises.cohort')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_logs', to='exercises.module')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['cohort', 'module'], name='quiz_log_cohort_module_idx'), models.Index(fields=['completed_at'], name='quiz_log_completed_idx')],
            },
        ),
    ]
