# Generated by Django 5.2.3 on 2025-10-13 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0020_quizlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptEval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ok', models.BooleanField(blank=True, help_text='True=good, False=bad, None=unknown', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Free-form annotation notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_annotations', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='exercises.attempt')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['annotator', 'created_at'], name='attempteval_annotator_idx')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'annotator'), name='unique_eval_per_annotator_attempt')],
            },
        ),
    ]
