# Generated by Django 5.2.7 on 2025-11-05 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0021_attempteval'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, help_text='Store image as binary data', null=True)),
                ('upload_token', models.CharField(db_index=True, help_text='Unique token for unauthenticated upload', max_length=128, unique=True)),
                ('uploaded_at', models.DateTimeField(blank=True, help_text='When the image was uploaded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_type', models.CharField(default='image/jpeg', help_text='MIME type of the image', max_length=50)),
                ('token_expires_at', models.DateTimeField(help_text='When the upload token expires')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exercises.attempt')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['attempt', 'created_at'], name='exercises_a_attempt_49ff4a_idx'), models.Index(fields=['upload_token'], name='exercises_a_upload__847c4a_idx')],
            },
        ),
    ]
