# Generated by Django 5.2.7 on 2025-11-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0022_attemptimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='uses_images',
            field=models.BooleanField(default=False),
        ),
    ]
