# Generated by Django 5.2.7 on 2025-11-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0023_exercise_uses_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptimage',
            name='image',
            field=models.TextField(blank=True, help_text='Store image as base64 encoded string', null=True),
        ),
    ]
