# Generated by Django 5.2.7 on 2025-11-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0024_alter_attemptimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='uses_images',
            new_name='allow_image_upload',
        ),
    ]
