# Generated by Django 5.2.7 on 2025-11-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0025_rename_uses_images_exercise_allow_image_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttemptImage',
            new_name='TraceImage',
        ),
        migrations.RenameIndex(
            model_name='traceimage',
            new_name='exercises_t_attempt_6e9a1a_idx',
            old_name='exercises_a_attempt_49ff4a_idx',
        ),
        migrations.RenameIndex(
            model_name='traceimage',
            new_name='exercises_t_upload__a82adc_idx',
            old_name='exercises_a_upload__847c4a_idx',
        ),
        migrations.AlterField(
            model_name='traceimage',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exercises.trace'),
        ),
    ]
