# Generated by Django 5.2.7 on 2025-11-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0026_rename_attemptimage_traceimage_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='traceimage',
            name='exercises_t_attempt_6e9a1a_idx',
        ),
        migrations.RenameField(
            model_name='traceimage',
            old_name='attempt',
            new_name='trace',
        ),
        migrations.AddIndex(
            model_name='traceimage',
            index=models.Index(fields=['trace', 'created_at'], name='exercises_t_trace_i_90df90_idx'),
        ),
    ]
