# Generated by Django 5.2.8 on 2025-11-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0027_remove_traceimage_exercises_t_attempt_6e9a1a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceimage',
            name='image',
            field=models.BinaryField(blank=True, help_text='Store image as binary data', null=True),
        ),
    ]
