# Generated by Django 5.2.8 on 2025-11-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0028_alter_traceimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceimage',
            name='trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exercises.trace'),
        ),
    ]
