# Generated by Django 5.2.3 on 2025-11-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0029_alter_traceimage_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceimage',
            name='chain_position',
            field=models.IntegerField(default=0, help_text='Position in upload chain (0=first, max 2 for 3 photos total)'),
        ),
        migrations.AddField(
            model_name='traceimage',
            name='next_token',
            field=models.CharField(blank=True, help_text='Token for next photo in upload chain', max_length=128, null=True),
        ),
    ]
