# Generated by Django 5.2.8 on 2025-11-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0030_traceimage_chain_position_traceimage_next_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='assistant_complete_content',
            field=models.JSONField(blank=True, default=dict, help_text='Complete JSON response of the assistant.'),
        ),
    ]
