# Generated by Django 5.2.3 on 2025-11-30 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0031_mobileauthtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileauthtoken',
            name='token_type',
        ),
    ]
