# Generated by Django 5.2.3 on 2025-11-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0035_remove_mobileauthtoken_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileauthtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
