# Generated by Django 5.2.3 on 2025-12-05 22:00

from django.db import migrations, models


def migrate_system_prompt_to_override(apps, schema_editor):
    """
    Migrate existing system_prompt data to override_system_prompt field.
    """
    Course = apps.get_model('exercises', 'Course')
    for course in Course.objects.all():
        if course.system_prompt:
            course.override_system_prompt = course.system_prompt
            course.save(update_fields=['override_system_prompt'])


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0036_alter_mobileauthtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_prompt',
            field=models.TextField(blank=True, help_text='Course-level prompt for this specific course. Will be added at the end of the system prompt for all exercises in this course. It may contain information about the course contents, objectives, target audience, etc. You can also include a large amount of information about the course content itself (e.g. a summary of 5k words), so that in its answers, the AI will refer to parts of the course content itself. Also, you may include which notations to use, which concepts to avoid, etc.'),
        ),
        migrations.AddField(
            model_name='course',
            name='override_system_prompt',
            field=models.TextField(blank=True, help_text='Override the default system prompt used by the AI tutor for exercises in this course. Leave empty to use the global default (recommended).'),
        ),
        migrations.RunPython(migrate_system_prompt_to_override, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='course',
            name='system_prompt',
        ),
    ]
