# Generated by Django 5.2.3 on 2025-12-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0037_remove_course_system_prompt_course_course_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='system_prompt',
            field=models.TextField(blank=True, help_text="The system prompt sent to the LLM for this trace. Only set on the first trace. It's kept in this Trace for reference & debugging purposes.", null=True),
        ),
    ]
