# Generated by Django 5.2.3 on 2025-12-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0038_alter_trace_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileauthtoken',
            name='first_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
