# Generated by Django 5.2.8 on 2025-12-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0039_mobileauthtoken_first_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceimage',
            name='highlight_bboxes',
            field=models.JSONField(blank=True, default=list, help_text="List of bounding boxes with highlighting info. Format: [{'bbox': [x0, y0, x1, y1], 'color': 'yellow'}, ...]"),
        ),
    ]
