# Generated by Django 5.2.3 on 2025-12-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0040_add_highlight_bboxes_to_traceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='draft_notes',
            field=models.TextField(blank=True, help_text="AI-generated notes about this exercise (what worked, questions, suggestions). Format is a 'full text', not structured like a json."),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Whether this exercise is a draft (hidden from students until published).'),
        ),
    ]
