# Generated by Django 5.2.9 on 2025-12-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0041_exercise_draft_notes_exercise_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='is_draft',
        ),
    ]
