# Generated by Django 5.2.9 on 2025-12-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0042_remove_exercise_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='archived',
            field=models.BooleanField(default=False, help_text='Soft-deleted exercise, hidden from all views'),
        ),
        migrations.AddField(
            model_name='module',
            name='archived',
            field=models.BooleanField(default=False, help_text='Soft-deleted module, hidden from all views'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(condition=models.Q(('archived', True), ('visible', True), _negated=True), name='exercise_archived_must_be_invisible'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('archived', True), ('visible', True), _negated=True), name='module_archived_must_be_invisible'),
        ),
    ]
