# Generated by Django 5.2.9 on 2025-12-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0043_exercise_archived_module_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='chat_prompt',
        ),
    ]
