# Generated by Django 5.2.9 on 2025-12-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0044_remove_course_chat_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='channel',
            field=models.CharField(choices=[('exercise_guidance', 'Exercise Guidance'), ('learning_pathway', 'Learning Pathway'), ('authoring', 'Authoring'), ('study_chat', 'Study Chat'), ('question_generator', 'Question Generator')], default='exercise_guidance', help_text='Logical stream for this trace (e.g., guidance vs. pathway vs. authoring).', max_length=32),
        ),
    ]
