# Generated by Django 5.2.9 on 2026-01-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0045_add_question_generator_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mobile_first',
            field=models.BooleanField(default=False, help_text='If true, desktop users will see a banner recommending mobile usage for this course.'),
        ),
    ]
