# Generated by Django 5.2.9 on 2026-03-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0046_course_mobile_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileauthtoken',
            name='code',
            field=models.CharField(db_index=True, default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='mobileauthtoken',
            name='code_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
