# Generated by Django 5.2.9 on 2026-03-07 15:33

import random
from django.db import migrations, models


def backfill_mobile_auth_code(apps, schema_editor):
    MobileAuthToken = apps.get_model('exercises', 'MobileAuthToken')
    rng = random.SystemRandom()
    for token in MobileAuthToken.objects.filter(code__isnull=True).only('id'):
        token.code = f"{rng.randrange(0, 1_000_000):06d}"
        token.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0046_course_mobile_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileauthtoken',
            name='code',
            field=models.CharField(db_index=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='mobileauthtoken',
            name='code_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(backfill_mobile_auth_code, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mobileauthtoken',
            name='code',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
