"""
Django settings for exam_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Sentry configuration (production only)
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN and os.getenv('DJANGO_DEBUG', 'True') != 'True':
    import sentry_sdk
    import logging
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration
    
    def before_send_transaction(event, hint):
        """Filter out fast database queries (< 100ms) to save quota."""
        if event.get('type') == 'transaction':
            spans = event.get('spans', [])
            filtered_spans = []
            for span in spans:
                if span.get('op', '').startswith('db'):
                    # Calculate duration in milliseconds
                    duration_ms = (span.get('timestamp', 0) - span.get('start_timestamp', 0)) * 1000
                    # Keep only slow queries (>= 100ms)
                    if duration_ms >= 100:
                        filtered_spans.append(span)
                else:
                    # Keep all non-DB spans
                    filtered_spans.append(span)
            event['spans'] = filtered_spans
        return event
    
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            LoggingIntegration(
                sentry_logs_level=logging.WARNING,  # Send WARNING and above to Sentry Logs
            ),
        ],
        traces_sample_rate=0.2,
        send_default_pii=False,
        environment='production',
        enable_logs=True,  # Enable Sentry Logs feature
        before_send=lambda event, hint: event if event.get('level') != 'info' else None,
        before_send_transaction=before_send_transaction,
        _experiments={
            "profiles_sample_rate": 0.0,  # Disable profiling to save quota
        },
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, DJANGO_SECRET_KEY must be provided
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-insecure-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h for h in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if h]

# Allow ngrok tunnels automatically in DEBUG mode
if DEBUG:
    ALLOWED_HOSTS += ['.ngrok-free.app', '.ngrok.io', '.ngrok.app', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_jsonform',
    'django.contrib.humanize',
    'channels',

    # our apps
    'accounts',  # only used for custom user model (prefered language)
    'exercises',
    'evaluation',
    'authoring_tools',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'exam_project.ngrok_middleware.NgrokCSRFMiddleware',  # Auto-trust ngrok origins in DEBUG
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'exam_project.sentry_middleware.SentryContextMiddleware',  # Attach user context to Sentry
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'exam_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'exam_project.context_processors.sentry_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'exam_project.wsgi.application'
ASGI_APPLICATION = 'exam_project.asgi.application'

# Redis configuration (used by both Channels for quiz state storage)
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')

# Channel layers for WebSocket support
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'steacher'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'myverysecretpassword'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Strong password hashing (prefer Argon2, fall back to PBKDF2)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# OpenAI API Key
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY', '')
PUBLICAI_API_KEY = os.getenv('PUBLICAI_API_KEY', '')
GDX_API_KEY = os.getenv('GDX_API_KEY', '')
GROQ_API_KEY = os.getenv('GROQ_API_KEY')
SCALA_INTERPRETER_URL = os.getenv('SCALA_INTERPRETER_URL', 'http://localhost:8642')

# PWA settings
PWA_APP_NAME = "Steacher"
PWA_APP_DESCRIPTION = "Mobile learning with AI tutor"
PWA_APP_THEME_COLOR = "#00d1b2"  # Bulma primary

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Add the node_modules directory to the static files search path
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "node_modules",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS
# Default to permissive in DEBUG, strict in production via env var CORS_ALLOWED_ORIGINS
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [o for o in os.getenv('DJANGO_CORS_ALLOWED_ORIGINS', '').split(',') if o]
    CORS_ALLOW_CREDENTIALS = True

# Logging configuration for steacher
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'steacher.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'exercises.logic': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'exercises.views_students': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'exercises.views_teachers': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'exercises.views_mobile': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Auth redirects
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'

# Email configuration (console by default; Mailtrap API when configured)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'teachers@steacher.org')

# Mailtrap API configuration (faster than SMTP)
MAILTRAP_API_KEY = os.getenv('MAILTRAP_API_KEY')
if MAILTRAP_API_KEY:
    EMAIL_BACKEND = 'exercises.mailtrap_backend.MailtrapBackend'

MAIL_DOMAIN = os.getenv('MAIL_DOMAIN', 'steacher.org')

# Allow login by email or username
AUTHENTICATION_BACKENDS = [
    'exercises.auth_backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Use custom user model
AUTH_USER_MODEL = 'accounts.User'

# Session and cookie settings
# Keep users logged in longer with rolling expiration
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days in production; override with env if needed
SESSION_COOKIE_AGE = int(os.getenv('DJANGO_SESSION_COOKIE_AGE', SESSION_COOKIE_AGE))
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SAMESITE = os.getenv('DJANGO_SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.getenv('DJANGO_CSRF_COOKIE_SAMESITE', 'Lax')
# Frontend code reads CSRF token, so keep it non-HttpOnly
CSRF_COOKIE_HTTPONLY = False

# Use HTTPS-only cookies and enforce HTTPS in non-debug environments
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    CSRF_TRUSTED_ORIGINS = [o for o in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o]
    SECURE_SSL_REDIRECT = True if os.getenv('DJANGO_SECURE_SSL_REDIRECT', '').lower() in ('1', 'true', 'yes') else False
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REFERRER_POLICY = os.getenv('DJANGO_SECURE_REFERRER_POLICY', 'same-origin')
    # Close cross-origin opener unless needed by features
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
else:
    # In DEBUG mode, trust ngrok HTTPS tunnels for CSRF
    CSRF_TRUSTED_ORIGINS = [
        'http://127.0.0.1:8000',
        'http://localhost:8000',
        'https://*.ngrok-free.app',
        'https://*.ngrok.io',
        'https://*.ngrok.app',
    ]
