# Generated by Django 5.2.3 on 2025-09-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_superuser', True)), fields=('is_superuser',), name='unique_single_superuser'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_staff', False), ('is_superuser', True), _connector='OR'), name='non_superuser_cannot_be_staff'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_superuser', False), ('is_staff', True), _connector='OR'), name='superuser_must_be_staff'),
        ),
    ]
