# Generated by Django 5.2.3 on 2025-07-28 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name/title of the course that will be displayed to the user.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='A short description of the course that will be displayed to the user.')),
                ('llm_prompts', models.JSONField(blank=True, default=dict, help_text="LLM prompts per exercise type, e.g. {'turtle': 'Your prompt for turtle exercises...'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the exercice; not displayed to the user.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the exercice; not displayed to the user.')),
                ('exercise_type', models.CharField(help_text="Type of the exercice, e.g. 'multiple_choice', 'text', 'turtle', etc.", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='The order of the exercice within the course.')),
                ('exercise_data', models.JSONField(help_text='Contains fields like question, data-source, etc.')),
                ('answer_data', models.JSONField(default=dict, help_text='Contains fields like expected_result, hints, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.course')),
            ],
            options={
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False, help_text='True if the user has completed the exercise.')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuidanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.JSONField(help_text="Stores the user's submission and the LLM's response for a single turn.")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_logs', to='exercises.trace')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Filename like 'shop.sql', 'presentation.pptx'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description.', null=True)),
                ('content', models.BinaryField(help_text='Store any file type as binary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='exercises.exercise')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'exercise'), name='unique_name_per_exercise')],
            },
        ),
    ]
