# Generated by Django 5.2.3 on 2025-07-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='llm_prompts',
            field=models.JSONField(blank=True, default=dict, help_text="LLM prompts per exercise type, e.g. {'turtle': 'Your prompt for turtle exercises...'}"),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(blank=True, help_text='Calculated on backend', null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_answer',
            field=models.JSONField(help_text='Flexible answer format.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='A short description of the course that will be displayed to the user.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='The name/title of the course that will be displayed to the user.', max_length=200),
        ),
        migrations.AlterField(
            model_name='exerciceasset',
            name='content',
            field=models.BinaryField(help_text='Store any file type as binary.'),
        ),
        migrations.AlterField(
            model_name='exerciceasset',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description.', null=True),
        ),
        migrations.AlterField(
            model_name='exerciceasset',
            name='name',
            field=models.CharField(help_text="Filename like 'shop.sql', 'presentation.pptx'", max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='answer_data',
            field=models.JSONField(default=dict, help_text='Contains fields like expected_result, hints, etc.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the exercice; not displayed to the user.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_data',
            field=models.JSONField(help_text='Contains fields like question, data-source, etc.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(help_text="Type of the exercice, e.g. 'multiple_choice', 'text', 'turtle', etc.", max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The order of the exercice within the course.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(help_text='Title of the exercice; not displayed to the user.', max_length=200),
        ),
    ]
