# Generated by Django 5.2.3 on 2025-07-30 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceEval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ok', models.BooleanField(help_text='Whether the trace is considered correct or not. Null means not evaluated.', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback provided for this evaluation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_evals', to='exercises.trace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
