# Generated by Django 5.2.3 on 2025-08-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_traceeval'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='version',
            field=models.IntegerField(default=0, help_text='Version of the trace, can be used to track changes in the trace logic.'),
        ),
    ]
