# Generated by Django 5.2.3 on 2025-07-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exerciceasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='answer_data',
            field=models.JSONField(default=dict),
        ),
    ]
