# Generated by Django 5.2.3 on 2025-08-14 13:03

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_trace_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trace',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='The system prompt sent to the LLM for this trace, if debugging is enabled.', null=True),
        ),
        migrations.AddField(
            model_name='trace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trace',
            name='version',
            field=models.IntegerField(default=1, help_text='Version of the trace, can be used to track changes in the trace logic or prompt or eval version.'),
        ),
        migrations.AlterUniqueTogether(
            name='trace',
            unique_together={('user', 'exercise', 'version')},
        ),
    ]
