# Generated by Django 5.2.3 on 2025-08-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_trace_created_at_trace_system_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('python', 'Python'), ('multiple_choice', 'Multiple Choice'), ('sql', 'SQL'), ('turtle', 'Turtle'), ('programming', 'Programming')], default='python', help_text="Type of the exercice, e.g. 'multiple_choice', 'text', 'turtle', etc.", max_length=50),
        ),
    ]
