# Generated by Django 5.2.3 on 2025-08-21 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_course_scoped_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('python', 'Python'), ('multiple_choice', 'Multiple Choice'), ('sql', 'SQL'), ('turtle', 'Turtle')], default='python', help_text="Type of the exercice, e.g. 'multiple_choice', 'text', 'turtle', etc.", max_length=50),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name/title of the module that will be displayed to the user.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='A short description of the module that will be displayed to the user.')),
                ('order', models.PositiveIntegerField(default=0, help_text='The order of the module within the course.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='exercises.course')),
            ],
            options={
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.module'),
        ),
    ]
