# Generated by Django 5.2.3 on 2025-08-21 08:22

from django.db import migrations


def migrate_exercises_to_modules(apps, schema_editor):
    Course = apps.get_model('exercises', 'Course')
    Module = apps.get_model('exercises', 'Module')
    Exercise = apps.get_model('exercises', 'Exercise')

    for course in Course.objects.all():
        # Create a placeholder module for each course
        module, created = Module.objects.get_or_create(
            course=course,
            name='Module',
            defaults={'order': 0}
        )

        # Assign all exercises of this course to the new module
        Exercise.objects.filter(course=course).update(module=module)


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_alter_exercise_exercise_type_module_exercise_module'),
    ]

    operations = [
        migrations.RunPython(migrate_exercises_to_modules),
    ]
