# Generated by Django 5.2.3 on 2025-08-21 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_migrate_exercises_to_modules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['module', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('module', 'order')},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.module'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='course',
        ),
    ]
