# Generated by Django 5.2.3 on 2025-08-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_alter_exercise_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='visible',
            field=models.BooleanField(default=True, help_text='Whether the module is visible to students.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='visible',
            field=models.BooleanField(default=True, help_text='Whether the exercise is visible to students.'),
        ),
    ]


