# Generated by Django 5.2.3 on 2025-08-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_module_exercise_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visible',
            field=models.BooleanField(default=True, help_text='Whether the course is visible to students.'),
        ),
    ]


