# Generated by Django 5.2.3 on 2025-08-31 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_course_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('python', 'Python'), ('multiple_choice', 'Multiple Choice'), ('sql', 'SQL'), ('turtle', 'Turtle'), ('open_question', 'Open Question')], default='python', help_text="Type of the exercice, e.g. 'multiple_choice', 'text', 'turtle', etc.", max_length=50),
        ),
        migrations.CreateModel(
            name='StudentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Lowercased', max_length=254, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_invite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
