from django.core.management.base import BaseCommand
from exercises.models import Exercise, ExerciceAsset, Course, GuidanceLog, Trace
from django.contrib.auth.models import User


class Command(BaseCommand):
    help = 'Create sample multiple choice exercises'

    def handle(self, *args, **options):

        # Clear existing 
        Exercise.objects.all().delete()
        ExerciceAsset.objects.all().delete()
        Course.objects.all().delete()
        GuidanceLog.objects.all().delete()
        Trace.objects.all().delete()
        User.objects.filter(username='sampleuser').delete()
        
        # Create a sample user
        sample_user = User.objects.create_user(username='sampleuser', password='samplepass')
        
        # Create a SQL course
        sql_course = Course.objects.create(
            name='Introduction to Databases',
            description='A course for learning SQL basics and the relational model.',
            llm_prompts={
                'sql': '''### Specialized SQL Tutor Prompt

You will adopt the role and style defined in the **General Tutor Prompt**. As an **SQL** tutor, you will follow these specific instructions:

**Task Workflow**
Your task is to guide me through a SQL coding exercise using the Socratic method. Before providing feedback, double-check my work against the exercise requirements and your own analysis.

**Interaction Inputs**
You will receive my work in a structured format:
* **Hint Requested:** A `True` (if I pushed the 'Hint' button) or `False` (if I pushed the 'Run Query' button).
* **Student Message:** An optional text message from me, if I want to ask you a specific question.
* **Student Code:** The SQL code I have written.
* **Code Output:** The result of running my code against the database. **Always trust the provided output.**
* **Execution Errors:** Any error messages generated by the database engine.

**Response Requirements**
* When guiding me, reference the specific **line number** where I should make an edit.
* You may suggest up to **two improvements** at a time, but better suggest one improvement at a time and be concise.
''',
                'multiple_choice': '''### Specialized Multiple Choice Tutor Prompt

You will adopt the role and style defined in the **General Tutor Prompt**. As a tutor for **Certainty-Based Marking (CBM)** questions, you will follow these specific instructions:

**CBM Scoring Rules**
The student has been graded based on this matrix:
*   **Right** on a **Correct** option: +2
*   **Right** on an **Incorrect** option: -2
*   **Wrong** on a **Correct** option: -1
*   **Wrong** on an **Incorrect** option: +1
*   **Not Sure**: 0

**Interaction Input**
The user's message will contain a pre-calculated breakdown of their score. It will look like this:
```
Here are my answers:
- **Option A:** I chose 'notsure'; the correct answer is: wrong. **Score: 0**
- **Option B:** I chose 'right'; the correct answer is: correct. **Score: 2**
- **Option C:** I chose 'notsure'; the correct answer is: correct. **Score: 0**
- **Option D:** I chose 'wrong'; the correct answer is: wrong. **Score: 1**
**Total Score: 3 / 6 points.**
```

**Response Requirements**
1.  **State the Total Score First:** Begin your response by clearly and encouragingly stating the student's total score. Example: "Great job trying this out! You scored 3 out of a possible 6 points."
2.  **Provide a Socratic Breakdown:** Go through each option from the user's summary.
    *   For **correct, confident answers** (e.g., +2 points): Briefly affirm them. "You correctly identified that B was right."
    *   For **correctly identified wrong answers** (e.g., +1 point): Acknowledge their accurate assessment. "You were right to mark A as wrong."
    *   For **confident mistakes** (e.g., -2 points): This is the most important teaching opportunity. Do not just give the answer. Ask a guiding question using the `choice_explanations`. Example: "On option D, you marked 'Right' but it's actually incorrect, which is why you lost 2 points. The key reason is [...]. Why do you think that might be the case?"
    *   For **uncertainty** (e.g., 0 points): Encourage them to reflect. "For option C, you weren't sure. Let's think about it..."
3.  **Maintain a Guiding Tone:** Your goal is to help the student understand *why* they got the score they did and to build their knowledge and confidence for next time. Never be judgmental.
'''
            }
        )
        
        # SQL Exercise data
        sql_exercises_data = {
            'course': sql_course,
            'title': 'Hello SQL',
            'description': 'Hello world with SQL using minimalisting students db',
            'exercise_type': 'sql',
            'order': 1,
            'exercise_data': {
                "question": "For this first exercise, write an SQL query to _list all rows from the `students` table_.",
                "db": "students_v1.sql"
            },
            'answer_data': {
                "expected_result": [
                    {
                        "first_name": "Yoko",
                        "last_name": "Tsuno",
                        "city": None,
                        "age": 23
                    },
                    {
                        "first_name": "Raoul",
                        "last_name": "Chatigré",
                        "city": None,
                        "age": 17
                    }
                ],
                "correct_answers": [
                    {
                        "answer": "SELECT * FROM students;",
                        "explanation": "This is the most straightforward answer"
                    },
                    {
                        "answer": "SELECT first_name, last_name FROM students;",
                        "explanation": "This works too, but it was not specifically asked to select `first_name` and `last_name`. It's fine because it's the first ever sql query that the students will write, and maybe some students know some SQL already."
                    }
                ],
                "hints": [
                    "The command to list all entries from a database table has the form `SELECT * FROM {table name}`"
                ],
                "additional_context": "This is the first ever SQL exercice/command that the students will write. It's kind of the hello world in SQL for them. Focus on getting them on-board, not on details. Don't hesitate to give them a hint."
            }
        }
           
        # Create SQL exercise
        sql_exercise = Exercise.objects.create(**sql_exercises_data)
        # Create a Trace for the sample user and SQL exercise
        sql_trace = Trace.objects.create(exercise=sql_exercise, user=sample_user, complete=False)
        
        # Create associated SQL asset
        sql_content = """CREATE TABLE students
(
  first_name        VARCHAR, 
  last_name         VARCHAR,
  city              VARCHAR,
  age               INTEGER
);

INSERT INTO students (first_name, last_name, age) 
  VALUES ('Yoko', 'Tsuno', 23);

INSERT INTO students (first_name, last_name, age) 
  VALUES ('Raoul', 'Chatigré', 17);"""
                
        ExerciceAsset.objects.create(
            name="students_v1.sql",
            description="Sample students table with initial data",
            content=sql_content.encode('utf-8'),
            exercise=sql_exercise
        )

        # Multiple choice exercise
        mc_exercise = Exercise.objects.create(
            course=sql_course,
            title='Database Normalization',
            description='Understanding database design principles.',
            exercise_type='multiple_choice',
            order=2,
            exercise_data={
                'question': 'What is the main purpose of database normalization?',
                'choices': [
                    {
                        'id': 'a',
                        'text': 'To increase database size'
                    },
                    {
                        'id': 'b',
                        'text': 'To reduce data redundancy'
                    },
                    {
                        'id': 'c',
                        'text': 'To improve data integrity'
                    },
                    {
                        'id': 'd',
                        'text': 'To duplicate data across tables'
                    }
                ]
            },
            answer_data={
                'correct_answers': ['b', 'c'],
                'explanation': 'Database normalization is primarily used to reduce data redundancy and improve data integrity by organizing data efficiently.',
                'choice_explanations': {
                    'a': 'Incorrect - Normalization typically reduces database size by eliminating redundancy',
                    'b': 'Correct - This is the main purpose of normalization',
                    'c': 'Correct - Normalization improves data integrity by ensuring data consistency and reducing redundancy',
                    'd': 'Incorrect - Normalization reduces data duplication, not increases it'
                },
                'hints': [],
                'additional_context': ''
            }
        )
        # Create a Trace for the sample user and MC exercise
        mc_trace = Trace.objects.create(exercise=mc_exercise, user=sample_user, complete=False)

        # Python course with a single exercise
        python_course = Course.objects.create(
            name='Introduction to Python',
            description='A course for learning Python basics.',
            llm_prompts={
                'python': '''### Specialized Python Tutor Prompt

You will adopt the role and style defined in the **General Tutor Prompt**. As a **Python** tutor, you will follow these specific instructions:

**Task Workflow**
Your task is to guide me through a Python coding exercise using the Socratic method. Before providing feedback, double-check my work against the exercise requirements and your own analysis.

**Interaction Inputs**
You will receive my work in a structured format:

* **Hint Requested:** A `True` (if I pushed the 'Hint' button) or `False` (if I pushed the 'Run Query' button).
* **Student Message:** An optional text message from me, if I want to ask you a specific question.
* **Student Code:** The Python code I have written.
* **Code Output:** The result of running my code. **Always trust the provided output.**
* **Execution Errors:** Any error messages generated by the Python interpreter.

**Response Requirements**
* When guiding me, reference the specific **line number** where I should make an edit.
* You may suggest up to **two improvements** at a time, but better suggest one improvement at a time and be concise.
'''
            }
        )

        # Python exercise
        py_exercise = Exercise.objects.create(
            course=python_course,
            title='Hello Python',
            description='Hello world with Python using minimalisting students db',
            exercise_type='python',
            order=1,
            exercise_data={
                'question': 'For this first exercise, write a Python function that _prints "Hello, World!"_ to the console.'
            },
            answer_data={
                'correct_answers': [
                    {
                        'answer': 'print("Hello, World!")',
                        'explanation': 'This is the most straightforward answer'
                    }
                ],
                'expected_result': ['Hello, World!'],  # each element is a line of output
                'hints': [
                    "The console is the black box where the output is printed.", 
                    "Your code can print information in the console by using the `print` function.",
                    "Because it's a function, you need to call it with parentheses.",
                    "Inside the parentheses, you need to put the text you want to print, between quotes.",
                    "You can use single or double quotes, it doesn't matter. But if you start with a double quote, you need to end with a double quote. And vice versa."
                ],
                'additional_context': ''
            }
        )
        # Create a Trace for the sample user and Python exercise
        py_trace = Trace.objects.create(exercise=py_exercise, user=sample_user, complete=False)

        self.style.SUCCESS(
                f'Successfully created sample courses, exercises and assets'
        ) 